### ISSUE TITLE
Three miscellaneous questions

### ISSUE THREAD

**Issue by DanielTakeshi** [rmrao/dev-environment#1]
Thanks for this great resource @rmrao . I just have a few quick questions.

1. It appears that this is for Ubuntu systems, due to the `apt install` I see in the bash scripts. Do you use this on Mac OS X, while converting Linux-based commands to their OS X equivalent? I also see that you use iTerm instead of the default terminal on Mac. How much does this require integration with iTerm? [And just to be clear do you actually run Ubuntu on your Mac system?]

2. Do you use a spell checker when writing Markdown files? I have used this in my past vimrc files:

```
autocmd BufRead,BufNewFile *.md set spell spelllang=en_us
autocmd BufRead,BufNewFile *.tex set spell spelllang=en_us
autocmd BufRead,BufNewFile *.txt set spell spelllang=en_us
```

but am wondering if you have your own solution for this?

3. On my Ubuntu 16.04 machine, I ran `sudo ./install_vim.sh` to get my vimrc to match yours, and it looks like it completed with no errors. I open up a Markdown file, and now I am wondering if it is possible to highlight text with a mouse and then right-click to copy text? In the past with my very simple vimrc, I was able to do that. It seems like it's not as straightforward to do that anymore. Do you ever find yourself needing to sometimes copy text directly from a vim 'window'?

Thanks!!

**Comment by rmrao** [comment]
1. I don't use Ubuntu on my Mac ,it's running OS X. I don't actually use the install scripts directly on OS X because since there are a lot of differences between Ubuntu and OS X and it's not really easy to convert between them. One note is that if you want to use `YouCompleteMe` you need MacVim as well. I have all of these things working, generally, on my Mac and generally converting apt to brew will work. iTerm isn't completely required but I have noticed that the colors don't work properly in normal terminal.

2. I don't use a spell checker when writing Markdown files. That seems like a reasonable solution. There might also be a vim extension that does this for Markdown and other files.

3. Hmm you can highlight by using the `alt` or `option` key, which I use when I need it. Plausibly there's a better solution. If you find one, let me know!

**Comment by DanielTakeshi** [comment]
Thanks for the clarifications! I've been having a nice time time with this and am enjoying the auto-complete text, among other things.

For (1), when you mention that the colors don't work properly in normal terminal, does that also apply for your ssh connections? For example, on my Ubuntu 16 machine, I installed your vim package and everything looks good --- the color seems to be a green-ish / brown-ish theme that looks like a lighter version of Sublime text's default color scheme (e.g., [this one](https://sublime3-docs-zh.readthedocs.io/en/latest/customization/color_schemes.html)).

However, on my laptop, through my normal terminal, if I ssh into that same machine, and edit files with vim, it looks completely off. For example, here is me on my Mac laptop ssh-ing into my same Ubuntu 16 machine, and opening my `.vimrc` file with vim:

<img width="1680" alt="Screen Shot 2019-04-22 at 8 02 36 PM" src="https://user-images.githubusercontent.com/5532096/56550243-f5081680-6539-11e9-9952-2ee3d52ed753.png">


The screen looks completely black. Or were you referring to other issues with the color scheme?

Edit: to clarify, I'm highlighting some text in the above, which is colored yellow-ish.

**Comment by rmrao** [comment]
Yes that is a common issue it seems. Specifically editing vim over ssh, and editing vim in a tmux session both seem to have some issues. iTerm I believe solves the first problem, and for the second one, the .tmux.conf + setting the $TERM variable appropriately + a newer tmux version seems to fix things.

Glad you’ve found it useful! I have a hard time debugging it because I don’t really have the patience to launch a virtual box and test things whenever I make a change, so if you have issues or suggestions let me know!

-Roshan

**Comment by DanielTakeshi** [comment]
I just confirmed, editing vim over ssh when going from one Ubuntu machine to another doesn't seem to be a problem. It just appears to be an issue when I am sshing while typing through a Mac, and trying to connect to an Ubuntu machine.

I realized in my last message I didn't actually put in a screenshot of the color scheme from my Ubuntu machine. Here is what the colors look like on my end.

![Screenshot from 2019-04-23 09-12-06](https://user-images.githubusercontent.com/5532096/56597832-23243f80-65a8-11e9-9e6c-a127f777ef5c.png)


I will continue testing stuff later. I'll close this and probably re-visit ssh-ing and Mac stuff in a subsequent issue.
